//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int IDCC { get; set; }
        public Nullable<int> IDLC { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
    
        public virtual LoaiCong LoaiCong { get; set; }
        public virtual Luong Luong { get; set; }
    }
}
