//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int SOHD { get; set; }
        public Nullable<System.DateTime> DateBD { get; set; }
        public Nullable<System.DateTime> DateKT { get; set; }
        public Nullable<System.DateTime> DateKy { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> LanKy { get; set; }
        public string Duration { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
